server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Compression des fichiers texte
    gzip on;
    gzip_types text/css application/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Pas de cache sur le code : tes modifications sont visibles tout de suite
    location ~* \.(html|js|css)$ {
        add_header Cache-Control "no-cache";
    }
}
